security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_user:
            id: fos_user.user_provider.username

    firewalls:
        oauth_token:                                   # Everyone can access the access token URL.
            pattern: ^/oauth/v2/token
            security: false
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api_doc:
            pattern: ^/api/doc
            security: false
        api_registration:
            pattern: ^/api/register
            security: false
        api_user_confirm:
            pattern: ^/api/confirm
            security: false
        api:
            pattern: ^/api
            fos_oauth: true
            stateless: true
            anonymous: false
