AppBundle\Entity\Comment:
    type: entity
    table: comment
    repositoryClass: AppBundle\Repository\CommentRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        content:
            type: text
        publishedAt:
            type: datetime
            column: publishedAt
            gedmo:
                timestampable:
                    on: create
    manyToOne:
        post:
            targetEntity: AppBundle\Entity\Post
            inversedBy: comments
            joinColumn:
                name: post_id
                referencedColumnName: id
        author:
            targetEntity: AppBundle\Entity\User
            joinColumn:
                name: author_id
                referencedColumnName: id
                nullable: false
            gedmo:
                blameable:
                    on: create
    lifecycleCallbacks: {  }
